change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
categories:
  - title: 'ðŸš€ Features'
    labels:
      - 'feature'
  - title: 'ðŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'ðŸ§° Maintenance'
    label: 'chore'

autolabeler:
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'bug'
    branch:
      - '/bug\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
      - '*'

template: |
  ## Whats Changed

  $CHANGES
